[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[context.production]
  branch = "production"

[context.main]
  branch = "main"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
